# Generated by Django 4.1.3 on 2022-11-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_staff_remove_books_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='publishing_house',
            name='manager_contact_number',
        ),
    ]
