# Generated by Django 4.1.3 on 2022-11-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
