# Generated by Django 4.1.3 on 2022-11-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_publishing_house_manager_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing_house',
            name='manager_contact_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
